# ascend — Astro 風格的 Crystal 靜態站產生器。
# 這個檔只負責 require；可執行入口在 src/main.cr。
require "./ascend/version"
require "./ascend/errors"
require "./ascend/config"
require "./ascend/frontmatter"
require "./ascend/markdown"
require "./ascend/book"
require "./ascend/page"
require "./ascend/collection"
require "./ascend/renderer"
require "./ascend/feeds"
require "./ascend/css"
require "./ascend/builder"
require "./ascend/server"
require "./ascend/watcher"
require "./ascend/scaffold"
require "./ascend/cover"
require "./ascend/cli"
